[package]
name = "tracing_logger"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.24"
file-rotate = "0.7.3"
thread-id = "4.0.0"
tokio = {version="1.28.0", features=["full"]}
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-core = "0.1.30"
tracing-subscriber = "0.3.17"
